name: Push/PR Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pr_check:
    name: PR Check Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (self)
        uses: actions/checkout@v4

      - name: Install flutter
        uses: flutter-actions/setup-flutter@v4

      - name: Install top-level dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --line-length=100 --output=none --set-exit-if-changed .

      - name: Analyze files
        run: dart analyze
